### ISSUE TITLE
Fullscreen Script Error

### ISSUE THREAD

**Issue by Nalum** [PunchablePlushie/godot_ggs#3]
Installed v2.0 via the Godot Engine AssetLib tab.

I'm trying to implement the fullscreen setting as explained in the docs. I've added the setting as below in the screen shot.
![Screenshot_20210512_163043](https://user-images.githubusercontent.com/384180/118002323-6abcc600-b33f-11eb-8ee2-e94d5daff64c.png)

I have then setup the `fullscreen.gd` script on that setting:
```gd
extends Node
# value: bool
#	Whether window is fullscreen or not
# window_script_path: String
#	Path to the logic script that's used for changing window size
# window_setting_index: int/String
#	The index of the window size setting in the settings list


func main(value: Dictionary) -> void:
	OS.window_fullscreen = value["value"]
	
	## Execute the window size logic again, in case the player changed the
	# window size while the window was at fullscreen.
	if value["value"] == false:
		var script_resource: Script = load(value["window_script_path"])
		var script_instance: Object = script_resource.new()
		var current = ggsManager.settings_data[str(value["window_setting_index"])]["current"]
		script_instance.main(current)
	
	OS.center_window()
```

And added the control to the screen with the correct setting index.

However when I run the scene I am getting the following error:
> Invalid get index 'window_script_path' (on base: 'Dictionary').

Removing the `if` block in the above function removed the issue but I just thought I'd call it out as I don't see any mention of `window_script_path` on the [How to Use](https://github.com/PunchablePlushie/godot_ggs/wiki/How-to-Use) page

**Comment by PunchablePlushie** [comment]
Every logic script uses a sort of "structure" to work properly, as mentioned on the wiki.
The comment in the script explains the structure. So the dictionary you pass to the `fullscreen.gd` script *must* have three keys:
* `value` which is a boolean value, which is whether fullscreen is active or not.
*  `window_script_path` is the path that you're going to use for resizing the window size. This can be either `windows_size.gd` or `window_resolution.gd`, depending on which one you decided to use.
*  `window_setting_index` is the index of the setting that handles window size.

Here's an example:
<img src="https://i.imgur.com/I9LASkA.png">
In the above example, `window_script_path` points to the absolute path of `window_scale.gd` script, because that's the script that `01. window_size` setting uses. And `window_setting_index` is `1` because the index of `window_size` is `1`.

**Comment by Nalum** [comment]
Thanks for getting back to me.

I don't see any mention of `window_script_path` on the [How to Use](https://github.com/PunchablePlushie/godot_ggs/wiki/How-to-Use) page, but I probably missed it.

Happy to close this then :+1:
